# LEGAL NOTE:
# LATTICE (tm) - The Portable and standard Markdown Editor
# Copyright (C) 2026 Owner of blessini.com (a.k.a Blessia)
# email: blessia AT blessini.com
#
# GNU AFFERO GENERAL PUBLIC LICENSE V3 NOTICE:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# See LICENCE file in GitHUB root folder of the repository.
# END OF NOTE

[package]
name = "lattice"
version = "0.3.1"
description = "A Markdown Editor that respects standards"
authors = ["Blessia Blessini"]
edition = "2024"
default-run = "lattice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "lattice_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = []
integration-test = []

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify = "6.0"
sha2 = "0.10"
base64 = "0.22.1"
tauri-plugin-fs = "2.4.4"
image = "0.25.9"
tauri-plugin-dialog = "2"
log = "0.4.29"
tauri-plugin-log = "2"
dirs = "6.0.0"
chrono = "0.4.44"

[dev-dependencies]
tempfile = "3.24.0"
tauri = { version = "2", features = ["test"] }
url = "2"

[[test]]
name = "file_open_tests"
path = "tests/file_open_tests.rs"

[profile.dev]
opt-level = 0
debug = true
